name = "boat-rental-system"
main = "src/index.ts"
compatibility_date = "2026-02-18"

compatibility_flags = [ "nodejs_compat" ]

[[d1_databases]]
binding = "DB"
database_name = "boat_rental_db"
database_id = "2c401729-ca10-4885-8172-bf024696e8c3"   # ← UUID REAL AQUÍ

[vars]
JWT_SECRET = "seguro-2026"
