name = "boat-rental-system"
main = "src/index.ts"
compatibility_date = "2026-02-18"

[[d1_databases]]
binding = "DB"
database_name = "boat_rental_db"
database_id = "boats"   # ← cámbialo por tu ID real de D1

[vars]
JWT_SECRET = "321654"

# Opcional: si usas KV para sesiones
# [[kv_namespaces]]
# binding = "SESSION_KV"
# id = "tu-kv-id-aqui"
